name: CI RSpec Tests

on: [pull_request]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    container:
      image: ruby:3.0.3

    steps:
      - uses: actions/checkout@v3

      - name: Load Env variables
        uses: cardinalby/export-env-action@v1
        with:
          envFile: '.env.github'    
          expand: 'true'

      - name: Bundle install
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3 --path vendor/bundle
    
      - name: Run tests
        run: "bundle exec rails test"